examen2/api/urls.py
from django.urls import path
from api import views

app_name = "api"
urlpatterns = [
    
]

examen2/core/urls.py
from core import views
from django.urls import path

from .models import *

app_name = "core"
urlpatterns = [
    ##Estadio
    path('list1/stadium/',views.List1.as_view(), name="list1"),
    path('create/Stadium/',views.CreateStadium.as_view(), name="create1"),
    path('detail/Stadium/<int:pk>/', views.DetailStadium.as_view(), name= "detailone"),
    path('update/Stadium/<int:pk>/', views.UpdateStadium.as_view(), name= "Update1"),
    path('delete/Stadium/<int:pk>/', views.DeleteStadium.as_view(), name= "delete1"),
    ##Equipo
    path('list2/team/',views.List2.as_view(), name="list2"),
    path('create2/team/',views.CreateTeam.as_view(), name="create2"),
    path('detail/team/<int:pk>/', views.DetailTeam.as_view(), name= "detailtwo"),
    path('update/team/<int:pk>/', views.UpdateTeam.as_view(), name= "Update2"),
    path('delete/team/<int:pk>/', views.DeleteTeam.as_view(), name= "delete2"),
    ##Ciudad
    path('list3/city/',views.List3.as_view(), name="list3"),
    path('create3/city/',views.CreateCity.as_view(), name="create3"),
    path('detail/city/<int:pk>/', views.DetailCity.as_view(), name= "detailthree"),
    path('update/city/<int:pk>/', views.UpdateCity.as_view(), name= "Update3"),
    path('delete/city/<int:pk>/', views.DeleteCity.as_view(), name= "delete3"),
    


]

examen2/home/urls.py
from django.urls import path
from home import views

app_name = "home"
urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('information/', views.Information.as_view(), name="information")
]

examen2/principal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('', include("home.urls")),
]

examen2/templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<style>
  body {
    color: aliceblue;
    display: flex;
    flex-direction: column;
    min-height: 100vh;
    margin: 0;
    background-color: black;
    background-image: url(https://library.sportingnews.com/styles/twitter_card_120x120/s3/2022-01/nfl-logo-080521-getty-ftr_1l4ashi1tahe91uiujfrmf291p.jpg?itok=Ha0_Od9O);
    background-repeat: no-repeat;
    background-size: cover;
    background-attachment: fixed;
  }

  thead {
    color: aliceblue;
    background-color: rgba(0, 0, 0, 0.5);
  }

  thead {
    color: aliceblue;
    background-color: rgba(0, 0, 0, 0.5);
  }
  
  tbody {
    color: aliceblue;
    background-color: rgba(0, 0, 0, 0.5);
  }

</style>
<body>
  
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary navbar-transparent"> 
    <a class="navbar-brand" href="{% url 'home:index' %}">NFL</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home:index' %}">Inicio</a>
        </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:list1' %}">Estadio</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:list2' %}">Equipos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:list3' %}">Ciudades</a>
            </li>
           
        </ul>
    </div>
</nav>
      {% block content %}
      {% endblock content %}
      <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <footer class="text-center text-white" >
            <!-- Grid container -->
            <div class="container pt-4">
              <!-- Section: Social media -->
              <section class="mb-4">
                <!-- Facebook -->
                <a
                  class="btn btn-link btn-floating btn-lg text-dark m-1"
                  href="#!"
                  role="button"
                  data-mdb-ripple-color="dark"
                  ><i class="fab fa-facebook-f"></i
                ></a>
          
                <!-- Twitter -->
                <a
                  class="btn btn-link btn-floating btn-lg text-dark m-1"
                  href="#!"
                  role="button"
                  data-mdb-ripple-color="dark"
                  ><i class="fab fa-twitter"></i
                ></a>
          
                <!-- Google -->
                <a
                  class="btn btn-link btn-floating btn-lg text-dark m-1"
                  href="#!"
                  role="button"
                  data-mdb-ripple-color="dark"
                  ><i class="fab fa-google"></i
                ></a>
          
                <!-- Instagram -->
                <a
                  class="btn btn-link btn-floating btn-lg text-dark m-1"
                  href="#!"
                  role="button"
                  data-mdb-ripple-color="dark"
                  ><i class="fab fa-instagram"></i
                ></a>
          
                <!-- Linkedin -->
                <a
                  class="btn btn-link btn-floating btn-lg text-dark m-1"
                  href="#!"
                  role="button"
                  data-mdb-ripple-color="dark"
                  ><i class="fab fa-linkedin"></i
                ></a>
                <!-- Github -->
                <a
                  class="btn btn-link btn-floating btn-lg text-dark m-1"
                  href="#!"
                  role="button"
                  data-mdb-ripple-color="dark"
                  ><i class="fab fa-github"></i
                ></a>
              </section>
              <!-- Section: Social media -->
            </div>
            <!-- Grid container -->
          
            <!-- Copyright -->
            <div class="text-center text-dark p-3" style="background-color: rgba(0, 0, 0, 0.2);">
              © 2023 Copyright: NFL y asociados
              <a class="text-dark" href="https://mdbootstrap.com/"></a>
            </div>
            <!-- Copyright -->
          </footer>
</body>
</html>