avance2/gestionar/api/urls.py
from django.urls import path
from api import views



app_name = "api"


urlpatterns = [
    
]

avance2/gestionar/cplaest/urls.py
from django import views
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('', include("home.urls")),
]

avance2/gestionar/home/urls.py
from django.urls import path
from home import views



app_name = "home"


urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('about/', views.About.as_view(), name="about"),    
    path('identity/', views.Identity.as_view(), name="identity"),
    path('contact/', views.Contact.as_view(), name="contact"),
    path('rutas/', views.Rutas.as_view(), name="rutas"),
    path('forms/', views.Forms.as_view(), name="forms"),
]

avance2/gestionar/templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
      {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <style>
      body {
        display: flex;
        flex-direction: column;
        min-height: 100vh;
        margin: 0;
        background-color: black;
        background-image: url(https://cdnb.artstation.com/p/assets/images/images/060/187/233/large/luiz-fernando-20.jpg?1678024852);
        background-repeat: no-repeat;
        background-size: cover;
        background-attachment: fixed;
      }
      
      .main-content {
        margin: 90px 300px;
        display: flex;
        align-items: center;
        height: 50vh; /* Opcional para centrar verticalmente */
      }
      
footer {
    max-height: 200px; /* Cambia el valor según tus necesidades */
    overflow-y: auto;
    background-color: rgba(255, 255, 255);
    padding: 1px;
}
    </style>
  </head>
  <body style="display: flex; flex-direction: column; min-height: 100vh; margin: 0;">
    <div class="container" style="flex: 1;">
      <div class="row">
        <div class="col">
          <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a href="{% url 'home:index' %}" style="border: none; float: left;" class="active"><img src="{% static 'img/Logo PNG.png' %}" style="height: 30px; margin-top: 5px;" /></a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                 
                    </ul>
                  </li>

                </ul>
                <form class="d-flex" role="search">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" />
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
              </div>
            </div>
          </nav>
        </div>
      </div>
      <div class="row">
        <div class="col-2"></div>
        <div class="main-content">
            {% block content %}
            {% endblock %}
          </div>
      </div>
      <div class="row align-items-stretch">
        <div class="col">
            <footer class="text-center text-lg-start bg-blanck text-muted" style="display: flex; flex-direction: column; margin: 0;">
                <section>
              <div class="container text-center">
                <div class="row mt-3">
                  <div class="col-md-4 col-lg-4 col-xl-4 mb-6 footer-column" style="position: relative;">
                    <h6 align="left" class="text-uppercase fw-bold mb-6">Redes Sociales</h6>
                    <p align="left">
                      <a href="https://www.facebook.com/profile.php?id=61552843885228" target="blank" class="text-reset"><i class="mdi mdi-facebook"></i> Facebook</a>
                    </p>
                    <p align="left">
                      <a href="https://www.instagram.com/jointkodersalliance/" target="blank" class="text-reset"><i class="mdi mdi-instagram"></i> Instagram</a>
                    </p>
                    <p align="left">
                      <a href="https://twitter.com/JointKodersAlli" target="blank" class="text-reset"><i class="mdi mdi-twitter"></i> Twitter</a>
                    </p>
                    <p align="left">
                      <a href="https://www.tiktok.com/@itsakzzl" target="blank" class="text-reset"><i class="mdi mdi-tiktok"></i> TikTok</a>
                    </p>
                  </div>

                  <div class="col-md-4 col-lg-4 col-xl-4 mx-auto mb-md-0 mb-6 footer-column" style="position: relative;">
                    <a><h6 align="left" class="text-uppercase fw-bold mb-6">Productos</h6></a>
                    <p align="left">
                      <a href="{% static 'img/Formal.jpg' %}" target="blank" class="text-reset">Uniforme Formal</a>
                    </p>
                    <p align="left">
                      <a href="{% static 'img/Tipo polo.jpg' %}" target="blank" class="text-reset">Uniforme Polo</a>
                    </p>
                    <p align="left">
                      <a href="#!" target="blank" class="text-reset">Tazas</a>
                    </p>
                    <p align="left">
                      <a href="#!" target="blank" class="text-reset">Gorras</a>
                    </p>
                  </div>

                  <div class="col-md-4 col-lg-4 col-xl-4 mx-auto mb-md-0 mb-6 footer-column" style="position: relative;">
                    <a><h6 align="left" class="text-uppercase fw-bold mb-6">Contacto</h6></a>
                    <p align="left">
                      <a href="https://maps.app.goo.gl/n1xBh8oXKmCzzm6b9" target="_blank" class="text-reset"><i class="fas fa-map-marked-alt"></i> Tijuana, BC 11731, MX</a>
                    </p>
                    <p align="left">
                      <a href="mailto:jointkodersalliance@gmail.com" target="_blank" class="text-reset"><i class="mdi mdi-google-maps"></i> jointkodersalliance@gmail.com</a>
                    </p>
                    <p align="left">
                      <a href="https://wa.me/qr/HH2324AHZZJOP1" target="_blank" class="text-reset"><i class="mdi mdi-google-maps"></i> +52 (664) 369 2229</a>
                    </p>
                    <p align="left">
                      <a href="https://wa.me/qr/WPDXGSAZMNV3J1" target="_blank" class="text-reset"><i class="mdi mdi-google-maps"></i> +52 (664) 472 8545</a>
                    </p>
                  </div>
                </div>
              </div>
            </section>
          </footer>
        </div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
      $(document).ready(function () {
        var maxHeight = 0
        $('.footer-column').each(function () {
          var height = $(this).height()
          if (height > maxHeight) {
            maxHeight = height
          }
        })
        $('.footer-column').height(maxHeight)
      })
    </script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  </body>
</html>

avance2/gestionar/templates/base/baseadmin.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
      {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <style>
      body {
        display: flex;
        flex-direction: column;
        min-height: 100vh;
        margin: 0;
        background-color: black;
        background-image: url(https://cdnb.artstation.com/p/assets/images/images/060/187/233/large/luiz-fernando-20.jpg?1678024852);
        background-repeat: no-repeat;
        background-size: cover;
        background-attachment: fixed;
      }
      
      .main-content {
        margin: 90px 300px;
        display: flex;
        align-items: center;
        height: 50vh; /* Opcional para centrar verticalmente */
      }
      
footer {
    max-height: 200px; /* Cambia el valor según tus necesidades */
    overflow-y: auto;
    background-color: rgba(255, 255, 255);
    padding: 1px;
}
    </style>
  </head>
  <body style="display: flex; flex-direction: column; min-height: 100vh; margin: 0;">
    <div class="container" style="flex: 1;">
      <div class="row">
        <div class="col">
          <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a href="{% url 'home:index' %}" style="border: none; float: left;" class="active"><img src="{% static 'img/Logo PNG.png' %}" style="height: 30px; margin-top: 5px;" /></a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                      <a class="nav-link" >Rutas</a>
                    </li>
                      <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"></a>
                      <ul class="dropdown-menu">
                        <li>
                          <a class="dropdown-item" href="{% url 'home:forms' %}">Agregar Ruta</a>

                        </li>
                        <li>
                          <a class="dropdown-item" href="#">Editar Ruta</a>
                        </li>
                        <li>
                          <a class="dropdown-item" href="#">Eliminar Ruta</a>
                        </li>
                      </ul>
                    <li class="nav-item">
                      <a class="nav-link" >Empleados</a>
                    </li>
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"></a>
                      <ul class="dropdown-menu">
                        <li>
                          <a class="dropdown-item" href="#">Agregar Empleado</a>
                        </li>
                        <li>
                          <a class="dropdown-item" href="#">Editar Empleado</a>
                        </li>
                        <li>
                          <a class="dropdown-item" href="#">Eliminar Empleado</a>
                        </li>
                      </ul>
                    </li>
                      </ul>
                    </li>
                  </ul>
                    </ul>
                  </li>

                </ul>
                <form class="d-flex" role="search">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" />
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
              </div>
            </div>
          </nav>
        </div>
      </div>
      <div class="row">
        <div class="col-2"></div>
        <div class="main-content">
            {% block content %}
            {% endblock %}
          </div>
      </div>
      <div class="row align-items-stretch">
        <div class="col">
            <footer class="text-center text-lg-start bg-blanck text-muted" style="display: flex; flex-direction: column; margin: 0;">
                <section>
              <div class="container text-center">
                <div class="row mt-3">
                  <div class="col-md-4 col-lg-4 col-xl-4 mb-6 footer-column" style="position: relative;">
                    <h6 align="left" class="text-uppercase fw-bold mb-6">Redes Sociales</h6>
                    <p align="left">
                      <a href="https://www.facebook.com/profile.php?id=61552843885228" target="blank" class="text-reset"><i class="mdi mdi-facebook"></i> Facebook</a>
                    </p>
                    <p align="left">
                      <a href="https://www.instagram.com/jointkodersalliance/" target="blank" class="text-reset"><i class="mdi mdi-instagram"></i> Instagram</a>
                    </p>
                    <p align="left">
                      <a href="https://twitter.com/JointKodersAlli" target="blank" class="text-reset"><i class="mdi mdi-twitter"></i> Twitter</a>
                    </p>
                    <p align="left">
                      <a href="https://www.tiktok.com/@itsakzzl" target="blank" class="text-reset"><i class="mdi mdi-tiktok"></i> TikTok</a>
                    </p>
                  </div>

                  <div class="col-md-4 col-lg-4 col-xl-4 mx-auto mb-md-0 mb-6 footer-column" style="position: relative;">
                    <a><h6 align="left" class="text-uppercase fw-bold mb-6">Productos</h6></a>
                    <p align="left">
                      <a href="{% static 'img/Formal.jpg' %}" target="blank" class="text-reset">Uniforme Formal</a>
                    </p>
                    <p align="left">
                      <a href="{% static 'img/Tipo polo.jpg' %}" target="blank" class="text-reset">Uniforme Polo</a>
                    </p>
                    <p align="left">
                      <a href="#!" target="blank" class="text-reset">Tazas</a>
                    </p>
                    <p align="left">
                      <a href="#!" target="blank" class="text-reset">Gorras</a>
                    </p>
                  </div>

                  <div class="col-md-4 col-lg-4 col-xl-4 mx-auto mb-md-0 mb-6 footer-column" style="position: relative;">
                    <a><h6 align="left" class="text-uppercase fw-bold mb-6">Contacto</h6></a>
                    <p align="left">
                      <a href="https://maps.app.goo.gl/n1xBh8oXKmCzzm6b9" target="_blank" class="text-reset"><i class="fas fa-map-marked-alt"></i> Tijuana, BC 11731, MX</a>
                    </p>
                    <p align="left">
                      <a href="mailto:jointkodersalliance@gmail.com" target="_blank" class="text-reset"><i class="mdi mdi-google-maps"></i> jointkodersalliance@gmail.com</a>
                    </p>
                    <p align="left">
                      <a href="https://wa.me/qr/HH2324AHZZJOP1" target="_blank" class="text-reset"><i class="mdi mdi-google-maps"></i> +52 (664) 369 2229</a>
                    </p>
                    <p align="left">
                      <a href="https://wa.me/qr/WPDXGSAZMNV3J1" target="_blank" class="text-reset"><i class="mdi mdi-google-maps"></i> +52 (664) 472 8545</a>
                    </p>
                  </div>
                </div>
              </div>
            </section>
          </footer>
        </div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
      $(document).ready(function () {
        var maxHeight = 0
        $('.footer-column').each(function () {
          var height = $(this).height()
          if (height > maxHeight) {
            maxHeight = height
          }
        })
        $('.footer-column').height(maxHeight)
      })
    </script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  </body>
</html>