examen2/api/urls.py
from django.urls import path
from api import views

app_name = "api"
urlpatterns = [
    
]

examen2/core/urls.py
from core import views
from django.urls import path

from .models import *

app_name = "core"
urlpatterns = [
    ##Estadio
    path('list1/stadium/',views.List1.as_view(), name="list1"),
    path('create/Stadium/',views.CreateStadium.as_view(), name="create1"),
    path('detail/Stadium/<int:pk>/', views.DetailStadium.as_view(), name= "detailone"),
    path('update/Stadium/<int:pk>/', views.UpdateStadium.as_view(), name= "Update1"),
    path('delete/Stadium/<int:pk>/', views.DeleteStadium.as_view(), name= "delete1"),
    ##Equipo
    path('list2/team/',views.List2.as_view(), name="list2"),
    path('create2/team/',views.CreateTeam.as_view(), name="create2"),
    path('detail/team/<int:pk>/', views.DetailTeam.as_view(), name= "detailtwo"),
    path('update/team/<int:pk>/', views.UpdateTeam.as_view(), name= "Update2"),
    path('delete/team/<int:pk>/', views.DeleteTeam.as_view(), name= "delete2"),
    ##Ciudad
    path('list3/city/',views.List3.as_view(), name="list3"),
    path('create3/city/',views.CreateCity.as_view(), name="create3"),
    path('detail/city/<int:pk>/', views.DetailCity.as_view(), name= "detailthree"),
    path('update/city/<int:pk>/', views.UpdateCity.as_view(), name= "Update3"),
    path('delete/city/<int:pk>/', views.DeleteCity.as_view(), name= "delete3"),
    


]

examen2/principal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('', include("home.urls")),
]

examen2/core/models.py
from django.db import models


class City(models.Model):
    id = models.AutoField(primary_key=True)  
    ciudad = models.CharField(max_length=128, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'City'

class Stadium(models.Model):
    num = models.AutoField(primary_key=True)
    estadio = models.IntegerField(blank=True, null=True)  
    nombre = models.CharField(max_length=128, blank=True, null=True)
    description = models.CharField(max_length=256, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'Stadium'

class Team(models.Model):
    codigo = models.AutoField(primary_key=True)
    equipo = models.CharField(max_length=128, blank=True, null=True)
    liga = models.CharField(max_length=256, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'Team'

    

examen2/core/forms.py
from django import forms

from .models import *


class StadiumForm(forms.ModelForm):
    class Meta:
        model = Stadium
        fields = "__all__"
        exclude = ["num"]
        widgets = {
            "estadio": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el número del estadio"}),
            "nombre": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el nombre del estadio"}),
            "description": forms.Textarea(attrs={"class": "form-control", "rows": 3, "placeholder": "Ingrese la descripción del estadio"}),
        }

class UpdateStadiumForm(forms.ModelForm):
    class Meta:
        model = Stadium
        fields = "__all__"
        exclude = ["num"]
        widgets = {
            "estadio": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el número del estadio"}),
            "nombre": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el nombre del estadio"}),
            "description": forms.Textarea(attrs={"class": "form-control", "rows": 3, "placeholder": "Ingrese la descripción del estadio"}),
        }

class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = "__all__"
        exclude = ["codigo"]
        widgets = {
            "equipo": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el nombre del equipo"}),
            "liga": forms.Textarea(attrs={"class": "form-control", "rows": 3, "placeholder": "Ingrese la descripción de la liga"}),
        }

class UpdateTeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = "__all__"
        exclude = ["codigo"]
        widgets = {
            "equipo": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el nombre del equipo"}),
            "liga": forms.Textarea(attrs={"class": "form-control", "rows": 3, "placeholder": "Ingrese la descripción de la liga"}),
        }

class CityForm(forms.ModelForm):
    class Meta:
        model = City
        fields = "__all__"
        exclude = ["id"]
        widgets = {
            "ciudad": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el nombre de la ciudad"}),
        }


class UpdateCityForm(forms.ModelForm):
    class Meta:
        model = City
        fields = "__all__"
        exclude = ["id"]
        widgets = {
            "ciudad": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el nombre de la ciudad"}),
        }

class RelationshipForm(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    stadium = models.ForeignKey(Stadium, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

examen2/core/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from .forms import *
from .models import *

# Create your views here.

##Estadio

class List1(generic.View):
    template_name = "core/list1.html"
    context = {}

    def get(self, request, *args, **kwargs):
        queryset = Stadium.objects.all()
        self.context = {
            "stadiums": queryset  
        }
        return render(request, self.template_name, self.context)



class DetailStadium(generic.DetailView):
    template_name = "core/detail1.html"
    model = Stadium


class CreateStadium(generic.CreateView):
    template_name = "core/create1.html"
    model = Stadium
    form_class = StadiumForm
    success_url = reverse_lazy("core:list1")


class UpdateStadium(generic.UpdateView):
    template_name = "core/Update1.html"
    model = Stadium
    form_class = UpdateStadiumForm
    success_url = reverse_lazy("core:list1")

class DeleteStadium(generic.DeleteView):
    template_name = "core/delete1.html"
    model = Stadium
    success_url = reverse_lazy("core:list1")


##Equipos

class List2(generic.View):
    template_name = "core/list2.html"
    context = {}

    def get(self, request, *args, **kwargs):
        queryset = Team.objects.all()
        self.context = {
            "Team": queryset
        }
        return render(request, self.template_name,self.context)
    
class CreateTeam(generic.CreateView):
    template_name = "core/create2.html"
    model = Team
    form_class = TeamForm
    success_url = reverse_lazy("core:list2")

    def form_valid(self, form):
        
        return super().form_valid(form)




class DetailTeam(generic.DetailView):
    template_name = "core/detail2.html"
    model = Team

class UpdateTeam(generic.UpdateView):
    template_name = "core/Update2.html"
    model = Team
    form_class = UpdateTeamForm
    success_url = reverse_lazy("core:list2")

class DeleteTeam(generic.DeleteView):
    template_name = "core/delete2.html"
    model = Team
    success_url = reverse_lazy("core:list2")

##Ciudades

class List3(generic.View):
    template_name = "core/list3.html"
    context = {}

    def get(self, request, *args, **kwargs):
        queryset = City.objects.all()
        self.context = {
            "City": queryset
        }
        return render(request, self.template_name,self.context)

class CreateCity(generic.CreateView):
    template_name = "core/create3.html"
    model = City
    form_class = CityForm
    success_url = reverse_lazy("core:list3")

class DetailCity(generic.DetailView):
    template_name = "core/detail3.html"
    model = City

class UpdateCity(generic.UpdateView):
    template_name = "core/Update3.html"
    model = City
    form_class = UpdateCityForm
    success_url = reverse_lazy("core:list3")

class DeleteCity(generic.DeleteView):
    template_name = "core/delete3.html"
    model = City
    success_url = reverse_lazy("core:list3")
    

examen2/templates/core/Update1.html
{% extends "base/base.html" %}

{% block title %}
  Actualizar estadio
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-primary">Actualizar estadio</button>
        <a href="{% url 'core:list1' %}" class="btn btn-outline-warning">Cancelar</a>
    </form>
{% endblock content %}

examen2/templates/core/Update2.html
{% extends "base/base.html" %}

{% block title %}
  Actualizar equipos
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-primary">Actualizar equipo</button>
        <a href="{% url 'core:list2' %}" class="btn btn-outline-warning">Cancelar</a>
    </form>
{% endblock content %}

examen2/templates/core/Update3.html
{% extends "base/base.html" %}

{% block title %}
  Actualziar ciudades
{% endblock title %}

{% block content %}
<h1>Actualizar ciudad</h1>
<form method="post" class="form">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-outline-primary">Actualizar ciudad</button>
  <a href="{% url 'core:list3' %}" class="btn btn-outline-warning">Cancelar</a>
</form>
{% endblock content %}

examen2/templates/core/create1.html
{% extends "base/base.html" %}

{% block title %}
Añadir estadio de futbol
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success">Añadir estadio</button>
        <a href="{% url 'core:list1' %}" class="btn btn-outline-warning">Cancelar</a>
    </form>
{% endblock content %}

examen2/templates/core/create2.html
{% extends "base/base.html" %}

{% block title %}
Añadir equipo de futbol
{% endblock title %}

{% block content %}
<form action="" method="post" class="form">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-outline-success">Añadir Equipo</button>
  <a href="{% url 'core:list2' %}" class="btn btn-outline-warning">Cancelar</a>
</form>

{% endblock content %}

examen2/templates/core/create3.html
{% extends "base/base.html" %}

{% block title %}
Añadir ciudad
{% endblock title %}

{% block content %}
<h1>Agregar Ciudad</h1>
<form method="post" class="form">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-outline-success">Añadir Ciudad</button>
  <a href="{% url 'core:list3' %}" class="btn btn-outline-warning">Cancelar</a>
</form>
{% endblock content %}

examen2/templates/core/delete1.html
{% extends "base/base.html" %}

{% block title %}
  Eliminar estadio
{% endblock title %}

{% block content %}
<br>
<p>¿Desea eliminar el estadio {{ object.nombre }}?</p>
<form method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-outline-danger">Sí, Continuar</button>
  <a href="{% url 'core:list1' %}" class="btn btn-outline-warning">Cancelar</a>
</form>


{% endblock content %}

examen2/templates/core/delete2.html
{% extends "base/base.html" %}

{% block title %}
  Eliminar equipo
{% endblock title %}

{% block content %}
<p>¿Desea eliminar el equipo {{ object.nombre }}?</p>
<form method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-outline-danger">Sí, Continuar</button>
  <a href="{% url 'core:list2' %}" class="btn btn-outline-warning">Cancelar</a>
</form>
{% endblock content %}

examen2/templates/core/delete3.html
{% extends "base/base.html" %}

{% block title %}
  Eliminar Ciudad
{% endblock title %}

{% block content %}
<h1>Eliminar Ciudad</h1>
<p>¿Desea eliminar la ciudad {{ City.ciudad }}?</p>
<form method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-outline-danger">Sí, Continuar</button>
  <a href="{% url 'core:list3' %}" class="btn btn-outline-warning">Cancelar</a>
</form>
{% endblock content %}

examen2/templates/core/detail1.html
{% extends "base/base.html" %}

{% block title %}
  Detalles de los estadios
{% endblock title %}

{% block content %}
  <h1>Detalles de los estadios</h1>
    <p>Estadio: {{ stadium.nombre }}</p>
    <p>Descripción: {{ stadium.description }}</p>
    <p>Capacidad: {{ stadium.estadio }}</p>
  
  <a href="{% url 'core:list3' %}" class="btn btn-outline-warning">Regresar</a>
{% endblock content %}

examen2/templates/core/detail2.html
{% extends "base/base.html" %}

{% block title %}
  Detalles de los equipos
{% endblock title %}

{% block content %}
  <h1>Detalles de los equipos</h1>

    <p>Equipo: {{ team.equipo }}</p>
    <p>Liga: {{ team.liga }}</p>
  
  <a href="{% url 'core:list3' %}" class="btn btn-outline-warning">Regresar</a>
{% endblock content %}

examen2/templates/core/list1.html
{% extends 'base/base.html' %}

{% block title %} Lista estadios {% endblock title %}

{% block content %}


    <a href="{% url 'core:create1' %}" class="btn btn-outline-success form-control">Agregar un nuevo estadio</a>
    <h1>Listado de estadios</h1>
    <table class="table table-striped table-hover">
        <thead>
            <th>Codigo del estadio</th>
            <th>Nombre del estadio</th>
            <th>Descripcion del estadio</th>
            <th></th>
            <th></th>
            <th></th>

        </thead>
        <tbody>
            {% for stadiums in stadiums %}
                <tr>
                    <td>{{ stadiums.num }}</td>
                    <td>{{ stadiums.nombre }}</td>
                    <td>{{ stadiums.description }}</td>
                    <td><a href="{% url 'core:detailone' stadiums.num %}" class="btn btn-outline-info">Detalles</a></td>
                    <td><a href="{% url 'core:Update1' stadiums.num %}" class="btn btn-outline-warning">Actualizar</a></td>
                    <td><a href="{% url 'core:delete1' stadiums.num %}" class="btn btn-outline-danger">Eliminar</a></td>
                </tr>
            {% endfor %}
        </tbody>
        
    </table>
   
{% endblock content %}

examen2/templates/core/list2.html
{% extends 'base/base.html' %}

{% block title %} Lista de equipos {% endblock title %}

{% block content %}


    <a href="{% url 'core:create2' %}" class="btn btn-outline-success form-control">Añadir nuevo equipo</a>
    <h1>Lista de equipos</h1>
<table class="table">
  <thead>
    <tr>
      <th>Numero</th>
      <th>Nombre del equipo</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    {% for Teamm in Team %}
      <tr>
        <td>{{ Teamm.codigo }}</td>
        <td>{{ Teamm.equipo }}</td>
        <td>
          <a href="{% url 'core:detailtwo' Teamm.codigo %}" class="btn btn-outline-info">Detalles</a>
          <a href="{% url 'core:Update2' Teamm.codigo %}" class="btn btn-outline-warning">Actualizar</a>
          <a href="{% url 'core:delete2' Teamm.codigo %}" class="btn btn-outline-danger">Eliminar</a>
      </td>
      
      </tr>
    {% endfor %}
  </tbody>
</table>

    
{% endblock content %}

examen2/templates/core/list3.html
{% extends 'base/base.html' %}

{% block title %} Lista de ciudades {% endblock title %}

{% block content %}


    <a href="{% url 'core:create3' %}" class="btn btn-outline-success form-control">Añadir nueva ciudad</a>
    <h1>Lista de ciudades</h1>
    <table class="table table-striped table-hover">
        <thead>
            <th>Ciudad</th>
            <th></th>

        </thead>
        <tbody>
            {% for City in City %}
                <tr>
                    <td>{{ City.ciudad }}</td>
                    <td><a href="{% url 'core:detailthree' City.id %}" class="btn btn-outline-info"> Detalles </a></td>
                    <td><a href="{% url 'core:Update3' City.id %}" class="btn btn-outline-warning"> Actualizar</a></td>
                    <td><a href="{%  url 'core:delete3' City.id %}" class="btn btn-outline-danger">Eliminar</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
   
{% endblock content %}